### ISSUE TITLE
Importer filled /tmp-directory with tmp*epub files

### ISSUE THREAD

**Issue by dsk7** [montaggroup/montag#214]
After importing a large batch of files, the partition holding /tmp filled up with temporary files.

**Comment by dsk7** [comment]
Maybe relevant: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 851, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 724, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 464, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 328, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file importer.py, line 84

**Comment by hrzlgnm** [comment]
closing this, both pr's addressing this have been merged
