### ISSUE TITLE
Montag sometimes fails to start at boot, one can only see a stacktrace with a psutil.NoSuchProcess

### ISSUE THREAD

**Issue by hrzlgnm** [montaggroup/montag#216]
OS Ubuntu 18.10

**Comment by hrzlgnm** [comment]
```
Apr 01 20:54:02 knulp montag-services.py[1225]: Traceback (most recent call last):
Apr 01 20:54:02 knulp montag-services.py[1225]:   File "/home/pydb/pydb/montag-services.py", line 106, in <module>
Apr 01 20:54:02 knulp montag-services.py[1225]:     main()
Apr 01 20:54:02 knulp montag-services.py[1225]:   File "/home/pydb/pydb/montag-services.py", line 103, in main
Apr 01 20:54:02 knulp montag-services.py[1225]:     args.func(args)
Apr 01 20:54:02 knulp montag-services.py[1225]:   File "/home/pydb/pydb/montag-services.py", line 29, in do_start_services
Apr 01 20:54:02 knulp montag-services.py[1225]:     services_status = services.get_current_services_status()
Apr 01 20:54:02 knulp montag-services.py[1225]:   File "/home/pydb/pydb/pydb/services.py", line 101, in get_current_services_status
Apr 01 20:54:02 knulp montag-services.py[1225]:     p = psutil.Process(pid)
Apr 01 20:54:02 knulp montag-services.py[1225]:   File "/usr/lib/python2.7/dist-packages/psutil/__init__.py", line 336, in __init__
Apr 01 20:54:02 knulp montag-services.py[1225]:     self._init(pid)
Apr 01 20:54:02 knulp montag-services.py[1225]:   File "/usr/lib/python2.7/dist-packages/psutil/__init__.py", line 376, in _init
Apr 01 20:54:02 knulp montag-services.py[1225]:     raise NoSuchProcess(pid, None, msg)
Apr 01 20:54:02 knulp montag-services.py[1225]: psutil._exceptions.NoSuchProcess: psutil.NoSuchProcess no process found with pid 1595
```

**Comment by dsk7** [comment]
I am marking this a fixed as the corresponing PR is now merged.
